### ISSUE TITLE
Kanban board set up milestone [0] 

### ISSUE THREAD

**Issue by andersonlebon** [andersonlebon/recipeApp#11]
Here is the link to the project [kanban board](https://github.com/andersonlebon/recipeApp/projects/1)
We are three in this team:  
- [ ] Team member A is @andersonlebon,
- [ ] Team member B is @pasytchangwa, and
- [ ] Team member C is @toliboff

**Comment by oxenprogrammer** [comment]
Well done
